fullnameOverride: diginestai

replicaCount: 1

image:
  repository: neuronestai/diginestai-prod
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}