fullnameOverride: juristbot-ai

replicaCount: 1

image:
  repository: neuronestai/juristbot
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
